version: "3.9"

services:
  frontend:
    build:
      context: ./frontend    
      args:
        BACKEND1_URL: ${BACKEND1_URL}
        BACKEND2_URL: ${BACKEND2_URL}
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ./.env-docker      
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
      context: ./backend1   
    container_name: backend1
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    networks:
      - internal

  backend2:
    build:
      context: ./backend2   
    container_name: backend2
    networks:
      - internal       

networks:
  internal:
    driver: bridge