apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: backend1:latest   
          imagePullPolicy: IfNotPresent  
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend1-config
                  key: PORT            
            - name: BACKEND2_URL
              valueFrom:
                configMapKeyRef:
                  name: backend1-config
                  key: BACKEND2_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend1-service
spec:
  selector:
    app: backend1
  ports:
    - protocol: TCP
      port: 4001        # porta interna do cluster
      targetPort: 4001  # porta do container
      nodePort: 30001   # porta externa para o host
  type: NodePort

